### ISSUE TITLE
Hi ! Can you add tag of plugins 

### ISSUE THREAD

**Issue by ghost** [Joshet18/CustomScore#6]
_Can you add tags of plugins_ **PlayedTime** **KDR-Pe** **_Please!_** @Joshet18

**Comment by Joshet18** [comment]
Yes, I will add it in a few days.

**Comment by Joshet18** [comment]
![image](https://github.com/user-attachments/assets/7326fa29-75cc-4b35-99b6-6013e8fa3e5c)

**Comment by ghost** [comment]
thx <3

**Comment by ghost** [comment]
**But can u update the GitHub, poggit.pmmp.io page? :3**

**Comment by Joshet18** [comment]
If I can, I'll just polish everything to push it to poggit and github.
